# Generated by Django 5.2 on 2025-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_policy_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
