# Generated by Django 5.2 on 2025-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_policy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='providerim',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
