# Generated by Django 5.2 on 2025-04-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myapp.policy'),
        ),
    ]
