# Generated by Django 5.2 on 2025-04-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_features_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('alt_call_date', models.DateField()),
                ('call_time', models.CharField(choices=[('9-12', '9:00 AM - 12:00 PM'), ('12-3', '12:00 PM - 3:00 PM'), ('3-6', '3:00 PM - 6:00 PM')], max_length=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='myapp.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
