# Generated by Django 5.2 on 2025-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_method',
            field=models.CharField(choices=[('phone call', 'Phone Call'), ('video call', 'Video Call')], default='phone call', max_length=20),
        ),
    ]
