# Generated by Django 5.2 on 2025-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_call_call_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='question',
            field=models.TextField(default='What is covered under this insurance policy?'),
        ),
    ]
