# Generated by Django 5.2 on 2025-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_call_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='topics',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
