# Generated by Django 5.2 on 2025-04-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_call_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.FileField(upload_to='documents/identity/')),
                ('address', models.FileField(upload_to='documents/address/')),
                ('income', models.FileField(upload_to='documents/income/')),
                ('medical_history', models.FileField(blank=True, null=True, upload_to='documents/medical/')),
                ('prev_insurance', models.FileField(blank=True, null=True, upload_to='documents/previous_insurance/')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
