# Generated by Django 5.2 on 2025-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
