# Generated by Django 5.2 on 2025-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='document',
            field=models.FileField(default='documents/default.pdf', upload_to='documents/'),
        ),
    ]
