# Generated by Django 5.2 on 2025-04-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_booking_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.document'),
        ),
    ]
