# Generated by Django 5.2 on 2025-04-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_payment_id',
        ),
    ]
