# Generated by Django 5.2 on 2025-04-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_reason', models.TextField()),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(upload_to='claims/documents/')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='under_review', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='myapp.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='myapp.user')),
            ],
        ),
    ]
