# Generated by Django 5.2 on 2025-04-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxary', 'Luxury')], max_length=20)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='myapp.user')),
            ],
        ),
    ]
