# Generated by Django 5.2 on 2025-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_carinsurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinsurance',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='carinsurance',
            name='user',
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
