# Generated by Django 5.2 on 2025-04-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='myapp.user'),
        ),
    ]
