# Generated by Django 5.2 on 2025-04-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_policy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='myapp.user'),
        ),
    ]
