# Generated by Django 5.2 on 2025-04-26 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_user_created_at_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
