# Generated by Django 5.2 on 2025-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_document_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
